load("//buck2:reindeer_rules.bzl", "app_rust_library")
load("//build:targets.bzl", "BPANN_CRATES", "BPANN_TEST_CRATES", "RUST_EDITION")

filegroup(
    name = "bpann-source",
    srcs = glob(["src/**/*.rs"]) + ["Cargo.toml"],
    visibility = ["PUBLIC"],
)

app_rust_library(
    name = "bpann",
    srcs = glob(["src/**/*.rs"]),
    crate = "bpann",
    crate_root = "src/lib.rs",
    edition = RUST_EDITION,
    visibility = ["PUBLIC"],
    deps = ["//rust:" + crate for crate in BPANN_CRATES] + ["//rust/crates/wire:wire"],
)

rust_test(
    name = "bpann-unit",
    srcs = glob(["src/**/*.rs"]),
    crate = "bpann",
    crate_root = "src/lib.rs",
    edition = RUST_EDITION,
    visibility = ["//buck2/tests:all"],
    deps = ["//rust:" + crate for crate in BPANN_TEST_CRATES] + ["//rust/crates/wire:wire"],
)
