load("@crates//:defs.bzl", "aliases", "crate_deps", "crate_edition")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")
load("//build:targets.bzl", "BPANN_CRATES", "BPANN_TEST_CRATES")

package(default_visibility = ["//visibility:public"])

exports_files(["Cargo.toml"])

rust_library(
    name = "bpann",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    crate_root = "src/lib.rs",
    edition = crate_edition(),
    deps = crate_deps(BPANN_CRATES) + [
        "//rust/crates/wire",
    ],
)

rust_test(
    name = "bpann_test",
    crate = ":bpann",
    aliases = aliases(normal_dev = True, proc_macro_dev = True),
    deps = crate_deps(BPANN_TEST_CRATES) + [
        "//rust/crates/wire",
    ],
    rustc_env = {
        "CARGO_MANIFEST_DIR": "rust/crates/bpann",
    },
)
