def python_wheel(
        name,
        extension,
        extension_suffix,
        fixture_srcs,
        license,
        notice,
        package,
        platform_tag,
        python_abi,
        python_requires,
        python_srcs,
        readme,
        runtime_libraries,
        target_compatible_with,
        version):
    """Builds a deterministic version-specific CPython wheel."""
    filename = "{}-{}-{}-{}-{}.whl".format(
        package,
        version,
        python_abi,
        python_abi,
        platform_tag,
    )
    native.genrule(
        name = name,
        srcs = python_srcs + fixture_srcs + runtime_libraries + [extension, license, notice, readme],
        out = filename,
        cmd = " ".join([
            "$(exe //buck2/wheel:pack)",
            "--src-dir",
            "$SRCDIR",
            "--out",
            "$OUT",
            "--package",
            package,
            "--version",
            version,
            "--platform-tag",
            platform_tag,
            "--python-abi",
            python_abi,
            "--python-requires",
            "'{}'".format(python_requires),
            "--readme",
            readme,
            "--extension-suffix",
            extension_suffix,
        ]),
        target_compatible_with = target_compatible_with,
        visibility = ["PUBLIC"],
    )
