#!/bin/sh
set -eu

repo_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "$repo_dir"

environment=ennx
if [ "${1:-}" = "cuda" ]; then
    environment=ennx-py312
fi

exec pixi run -e "$environment" ./buck2w --isolation-dir dev run //rust/crates/dev-cli:ennx -- "$@"
