module(
    name = "ennx",
    version = "0.0.0",
)

bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "openmp", version = "21.1.5.bcr.2")
bazel_dep(name = "apple_support", version = "1.24.2")
bazel_dep(name = "rules_cc", version = "0.2.17")
bazel_dep(name = "rules_foreign_cc", version = "0.15.1")
bazel_dep(name = "rules_python", version = "2.2.0")
bazel_dep(name = "rules_rust", version = "0.71.3")
bazel_dep(name = "buildifier_prebuilt", version = "8.5.1.2")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.defaults(python_version = "3.13")
python.toolchain(python_version = "3.13")
use_repo(python, "python_3_13")

http_archive = use_repo_rule(
    "@bazel_tools//tools/build_defs/repo:http.bzl",
    "http_archive",
)

http_archive(
    name = "faiss_src",
    build_file = "//bazel/faiss:BUILD.faiss.bazel",
    sha256 = "7f3c4ed9aec3bd7524382862f5fcbd4d8984e2a8979ff3bdb2c0bcea5144149e",
    strip_prefix = "faiss-1.14.3",
    urls = ["https://github.com/facebookresearch/faiss/archive/refs/tags/v1.14.3.tar.gz"],
)

http_archive(
    name = "openblas_src",
    build_file = "//bazel/openblas:BUILD.openblas.bazel",
    sha256 = "f8a1138e01fddca9e4c29f9684fd570ba39dedc9ca76055e1425d5d4b1a4a766",
    strip_prefix = "OpenBLAS-0.3.32",
    urls = ["https://github.com/OpenMathLib/OpenBLAS/releases/download/v0.3.32/OpenBLAS-0.3.32.tar.gz"],
)

http_archive(
    name = "usearch_src",
    build_file = "//bazel/usearch:BUILD.usearch.bazel",
    sha256 = "1cd7f672d20412962c457b11c858c6c5aecb949808a5345a95e1d671112bcf72",
    strip_prefix = "usearch-2.26.0",
    type = "tar.gz",
    urls = ["https://static.crates.io/crates/usearch/2.26.0/download"],
)

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2021",
    versions = ["1.88.0"],
)
use_repo(rust, "rust_toolchains")

register_toolchains("@rust_toolchains//:all")

crate = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")
crate.from_cargo(
    name = "crates",
    cargo_lockfile = "//rust:Cargo.lock",
    lockfile = "//:Cargo.Bazel.lock",
    manifests = ["//rust:Cargo.toml"],
    supported_platform_triples = [
        "aarch64-apple-darwin",
        "x86_64-pc-windows-msvc",
        "x86_64-unknown-linux-gnu",
    ],
)
crate.spec(
    package = "metal",
    repositories = ["accelerator_crates"],
    version = "0.33.0",
)
crate.spec(
    package = "opencl3",
    repositories = ["accelerator_crates"],
    version = "0.12.3",
)
crate.from_specs(
    name = "accelerator_crates",
    cargo_lockfile = "//:Cargo.Accelerators.lock",
    lockfile = "//:Cargo.Accelerators.Bazel.lock",
    supported_platform_triples = [
        "aarch64-apple-darwin",
        "x86_64-pc-windows-msvc",
        "x86_64-unknown-linux-gnu",
    ],
)
use_repo(crate, "accelerator_crates", "crates")
