[workspace]
name = "ennx"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]

[feature.ennx.dependencies]
numpy = "*"
scipy = "*"

[feature.test.dependencies]
pytest = "*"
click = "*"

[feature.gp.dependencies]
pytorch = ">=2.0"
gpytorch = ">=1.11"

[feature.py312.dependencies]
python = "3.12.*"

[feature.py313.dependencies]
python = "3.13.*"

[feature.py314.dependencies]
python = "3.14.*"

[environments]
ennx = { features = ["ennx", "test", "gp", "py313"], no-default-feature = true }
ennx-py312 = { features = ["ennx", "test", "py312"], no-default-feature = true }
ennx-py314 = { features = ["ennx", "test", "py314"], no-default-feature = true }
