[workspace]
name = "ennx"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]

[feature.ennx.dependencies]
numpy = "*"
scipy = "*"

[feature.ennx.pypi-dependencies]
botorch = "==0.18.1"
optuna = "==5.0.0"
ax-platform = "==1.3.1"

[feature.test.dependencies]
pytest = "*"
click = "*"

[feature.gp.dependencies]
pytorch = ">=2.0"
gpytorch = ">=1.11"

[feature.py312.dependencies]
python = "3.12.*"

[feature.py313.dependencies]
python = "3.13.*"

[feature.py314.dependencies]
python = "3.14.*"

[feature.build-tools.dependencies]
git = "*"
git-lfs = "*"

[feature.build-tools.target.linux-64.dependencies]
auditwheel = "*"
patchelf = "*"
binutils = "*"

[feature.build-tools.target.linux-aarch64.dependencies]
auditwheel = "*"
patchelf = "*"
binutils = "*"

[environments]
build-tools = { features = ["build-tools"], no-default-feature = true }
ennx = { features = ["ennx", "test", "gp", "py313"], no-default-feature = true }
ennx-py312 = { features = ["ennx", "test", "py312"], no-default-feature = true }
ennx-py314 = { features = ["ennx", "test", "py314"], no-default-feature = true }
