load(":cxx.bzl", "ennx_cxx_toolchain")
load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")
load("@prelude//toolchains:python.bzl", "remote_python_toolchain")
load("@prelude//tests:test_toolchain.bzl", "noop_test_toolchain")
load("@prelude//toolchains:remote_test_execution.bzl", "remote_test_execution_toolchain")
load(":rust.bzl", "pinned_rust_toolchain")

config_setting(
    name = "build-tool",
    constraint_values = ["prelude//cfg/exec_platform/marker:is_exec_platform[true]"],
)

pinned_rust_toolchain(name = "rust")
ennx_cxx_toolchain(name = "cxx")
system_genrule_toolchain(name = "genrule", visibility = ["PUBLIC"])
remote_python_toolchain(name = "python", visibility = ["PUBLIC"])
noop_test_toolchain(name = "test", visibility = ["PUBLIC"])
remote_test_execution_toolchain(name = "remote_test_execution", visibility = ["PUBLIC"])
