# Generated by `./ennx toolchain sync`; do not edit by hand.
RUST_CHANNEL = "nightly-2026-09-29"
RUST_DATE = "2026-09-29"
RUST_EDITION = "2024"

RUST_ARCHIVES = {
    "aarch64-apple-darwin": (
        "e76cb7ea5f41feb883ee7ed89bd71f48ec029eca9605d3aa757d952bd6a153be",
        "9aff93c17c08536ce435c52a684994bc53ac4124bb96f31a2a4e8a0c90455cef",
        "d9af2c518fd2514cc32f101b28bbf7ac75ce1b69951dc8219c7b2dd422cfea32",
    ),
    "aarch64-unknown-linux-gnu": (
        "651734f660be3f83022f4a627c920753e19e79a7e6c0ee1e6c41f4f78c59767d",
        "e82df06b42c26e25b4f2171ae29a87213f4058c1bbedbd9d89b3d001f9f780f5",
        "7d92cb99305acc58e904581cfaa229b567e90461577aa1b68f92eb1100eb4757",
    ),
    "x86_64-unknown-linux-gnu": (
        "dba6569dd43bf3566bea07621fd270baac5ee75ca70a729c45bcef46f2725b9f",
        "248ea6470f93feda237c4e69e8361003145271227075f38f889f65f9eb4ed12e",
        "5131f8217dfa2d986a53de6fb8df032409e9f9cddcbbc6f81bd5e289478f5b5b",
    ),
}
