filegroup(
    name = "turbo-enn.toml",
    srcs = [
        "code-pretrain.toml",
        "code-pretrain-family-learned.toml",
        "code-pretrain-perturbation-gaussian.toml",
        "code-pretrain-perturbation-rademacher.toml",
        "code-pretrain-ablation-global-reliability.toml",
        "code-pretrain-ablation-global-turbo.toml",
        "code-pretrain-ablation-local-reliability.toml",
        "code-pretrain-ablation-local-turbo.toml",
        "turbo-enn-one-round.toml",
        "moe-layer.toml",
        "turbo-enn.toml",
        "turbo-enn-trace.toml",
    ],
    visibility = ["PUBLIC"],
)
