buildscript.run = false

['cfg(target_os = "macos")']
extra_deps = ["//buck2/native:openmp-macos"]
rustc_flags = [
  "-Clink-arg=-undefined",
  "-Clink-arg=dynamic_lookup",
  "-Clink-arg=-Wl,-rpath,@loader_path/.dylibs",
]
