//! Low-Latency Multi-Trust Region (TuRBO-M) state engine.
//!
//! Maintains $M$ concurrent trust regions in contiguous array memory (SoA layout)
//! for zero-allocation CPU SIMD operations and direct GPU buffer mirroring.

use ndarray::{Array1, Array2, ArrayView1, ArrayView2};
use rand::RngCore;
use serde::{Deserialize, Serialize};

use crate::trust_region::{TRLengthConfig, TrustRegionError};

/// Policy for sharing observations across multiple trust regions.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SharingPolicy {
    /// Shared: all observations update every region whose bounds contain the point.
    Shared,
    /// NearestCenter: observation updates only the nearest region center.
    NearestCenter,
    /// Independent: observations are assigned only to their generating region.
    Independent,
}

impl Default for SharingPolicy {
    fn default() -> Self {
        Self::Shared
    }
}

/// Configuration for Multi-Trust Region state machine.
#[derive(Debug, Clone, PartialEq)]
pub struct MultiTrustRegionConfig {
    /// Number of concurrent trust regions (M).
    pub num_regions: usize,
    /// Trust region length configuration parameters.
    pub length: TRLengthConfig,
    /// Consecutive successes required before region expansion.
    pub succ_tolerance: i32,
    /// Consecutive failures allowed before region contraction.
    pub fail_tolerance: i32,
    /// Observation sharing policy across regions.
    pub sharing_policy: SharingPolicy,
    /// UCB exploration weight used to divide a candidate budget.
    pub exploration: f64,
    /// Minimum normalized Hamming distance between selected perturbation seeds.
    pub min_seed_distance: f64,
}

impl MultiTrustRegionConfig {
    pub fn new(num_regions: usize, length: TRLengthConfig) -> Self {
        Self {
            num_regions,
            length,
            succ_tolerance: 3,
            fail_tolerance: 5,
            sharing_policy: SharingPolicy::Shared,
            exploration: 1.0,
            min_seed_distance: 0.0,
        }
    }
}

/// A contiguous candidate range assigned to one trust region.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RegionBatch {
    pub region: usize,
    pub start: usize,
    pub len: usize,
}

/// A scored perturbation candidate.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct RegionCandidate {
    pub index: usize,
    pub region: usize,
    pub seed: u64,
    pub score: f64,
}

/// Multi-Trust Region engine storing $M$ regions in contiguous flat memory.
#[derive(Debug, Clone)]
pub struct MultiTrustRegionState {
    num_regions: usize,
    num_dim: usize,

    /// Contiguous center matrix of shape `[num_regions, num_dim]` in unit hypercube `[0, 1]^d`.
    pub centers: Array2<f64>,
    /// Contiguous length vector of shape `[num_regions]`.
    pub lengths: Array1<f64>,
    /// Best observed scalar value per region of shape `[num_regions]`.
    pub incumbents_y: Array1<f64>,
    /// Success counters per region.
    pub succ_counts: Vec<i32>,
    /// Failure counters per region.
    pub fail_counts: Vec<i32>,
    /// Active mask per region (false when region needs restart).
    pub active_mask: Vec<bool>,
    /// Number of completed trials generated by each region.
    pub trial_counts: Vec<u64>,
    /// Online mean objective per region.
    pub mean_y: Array1<f64>,
    /// Online objective variance accumulator per region.
    pub m2_y: Array1<f64>,

    config: MultiTrustRegionConfig,
}

impl MultiTrustRegionState {
    /// Initialize a new MultiTrustRegionState.
    pub fn new(
        num_dim: usize,
        config: MultiTrustRegionConfig,
        initial_centers: Option<&ArrayView2<f64>>,
        rng: &mut dyn RngCore,
    ) -> Result<Self, TrustRegionError> {
        if config.num_regions == 0 {
            return Err(TrustRegionError::InvalidParameter(
                "num_regions must be > 0".to_string(),
            ));
        }
        if !config.exploration.is_finite() || config.exploration < 0.0 {
            return Err(TrustRegionError::InvalidParameter(
                "exploration must be finite and non-negative".to_string(),
            ));
        }
        if !config.min_seed_distance.is_finite() || !(0.0..=1.0).contains(&config.min_seed_distance)
        {
            return Err(TrustRegionError::InvalidParameter(
                "min_seed_distance must be in [0, 1]".to_string(),
            ));
        }

        let num_regions = config.num_regions;
        let mut centers = Array2::zeros((num_regions, num_dim));

        if let Some(init) = initial_centers {
            if init.nrows() != num_regions || init.ncols() != num_dim {
                return Err(TrustRegionError::InvalidParameter(format!(
                    "initial_centers shape {:?} does not match [{}, {}]",
                    (init.nrows(), init.ncols()),
                    num_regions,
                    num_dim
                )));
            }
            centers.assign(init);
        } else {
            // Uniformly sample centers in unit hypercube [0, 1]^d
            for r in 0..num_regions {
                for d in 0..num_dim {
                    centers[[r, d]] = rand::Rng::gen_range(rng, 0.0..1.0);
                }
            }
        }

        let lengths = Array1::from_elem(num_regions, config.length.length_init);
        let incumbents_y = Array1::from_elem(num_regions, f64::NEG_INFINITY);
        let succ_counts = vec![0; num_regions];
        let fail_counts = vec![0; num_regions];
        let active_mask = vec![true; num_regions];
        let trial_counts = vec![0; num_regions];
        let mean_y = Array1::zeros(num_regions);
        let m2_y = Array1::zeros(num_regions);

        Ok(Self {
            num_regions,
            num_dim,
            centers,
            lengths,
            incumbents_y,
            succ_counts,
            fail_counts,
            active_mask,
            trial_counts,
            mean_y,
            m2_y,
            config,
        })
    }

    pub fn num_regions(&self) -> usize {
        self.num_regions
    }

    pub fn num_dim(&self) -> usize {
        self.num_dim
    }

    pub fn active_count(&self) -> usize {
        self.active_mask.iter().filter(|&&a| a).count()
    }

    pub fn sharing_policy(&self) -> SharingPolicy {
        self.config.sharing_policy
    }

    /// Divide a flat candidate budget among active regions with a UCB policy.
    pub fn allocate(&self, budget: usize) -> Result<Vec<RegionBatch>, TrustRegionError> {
        self.allocate_with(budget, &self.mean_y.view())
    }

    /// Allocate with objective-specific region utility.
    ///
    /// Utilities may be scalar trajectory values, hypervolume contributions,
    /// or feasibility scores. Larger values receive more candidates.
    pub fn allocate_with(
        &self,
        budget: usize,
        utility: &ArrayView1<f64>,
    ) -> Result<Vec<RegionBatch>, TrustRegionError> {
        if utility.len() != self.num_regions || utility.iter().any(|value| !value.is_finite()) {
            return Err(TrustRegionError::InvalidParameter(
                "region utility must contain one finite value per region".to_string(),
            ));
        }
        let active: Vec<usize> = self
            .active_mask
            .iter()
            .enumerate()
            .filter_map(|(r, &is_active)| is_active.then_some(r))
            .collect();
        if active.is_empty() {
            return Err(TrustRegionError::InvalidState(
                "no active trust regions".to_string(),
            ));
        }
        if budget == 0 {
            return Err(TrustRegionError::InvalidParameter(
                "candidate budget must be > 0".to_string(),
            ));
        }

        let total_trials = self.trial_counts.iter().sum::<u64>().max(1) as f64;
        if budget < active.len() {
            let mut ranked = active;
            ranked.sort_by(|&a, &b| {
                self.priority(b, 0, total_trials, utility[b])
                    .total_cmp(&self.priority(a, 0, total_trials, utility[a]))
                    .then_with(|| a.cmp(&b))
            });
            let mut start = 0;
            return Ok(ranked
                .into_iter()
                .take(budget)
                .map(|region| {
                    let batch = RegionBatch {
                        region,
                        start,
                        len: 1,
                    };
                    start += 1;
                    batch
                })
                .collect());
        }

        let mut counts = vec![1usize; self.num_regions];
        for _ in active.len()..budget {
            let region = active
                .iter()
                .copied()
                .max_by(|&a, &b| {
                    self.priority(a, counts[a], total_trials, utility[a])
                        .total_cmp(&self.priority(b, counts[b], total_trials, utility[b]))
                        .then_with(|| b.cmp(&a))
                })
                .expect("active regions are non-empty");
            counts[region] += 1;
        }

        let mut start = 0;
        Ok(active
            .into_iter()
            .map(|region| {
                let batch = RegionBatch {
                    region,
                    start,
                    len: counts[region],
                };
                start += batch.len;
                batch
            })
            .collect())
    }

    /// Sample variance of completed objectives for a region.
    pub fn variance(&self, region: usize) -> Option<f64> {
        let count = *self.trial_counts.get(region)?;
        (count > 1).then(|| self.m2_y[region] / (count - 1) as f64)
    }

    /// Select `num_arms` candidates globally while avoiding duplicate perturbations.
    pub fn select(
        &self,
        candidates: &[RegionCandidate],
        num_arms: usize,
    ) -> Result<Vec<RegionCandidate>, TrustRegionError> {
        if num_arms == 0 || num_arms > candidates.len() {
            return Err(TrustRegionError::InvalidParameter(format!(
                "num_arms {num_arms} is outside 1..={}",
                candidates.len()
            )));
        }
        if candidates
            .iter()
            .any(|c| c.region >= self.num_regions || !c.score.is_finite())
        {
            return Err(TrustRegionError::InvalidParameter(
                "candidate has an invalid region or score".to_string(),
            ));
        }

        let mut ranked = candidates.to_vec();
        ranked.sort_by(|a, b| {
            b.score
                .total_cmp(&a.score)
                .then_with(|| a.index.cmp(&b.index))
        });

        let mut selected = Vec::with_capacity(num_arms);
        for candidate in &ranked {
            if selected
                .iter()
                .all(|other: &RegionCandidate| self.seed_distance(candidate.seed, other.seed))
            {
                selected.push(*candidate);
                if selected.len() == num_arms {
                    return Ok(selected);
                }
            }
        }

        for candidate in ranked {
            if !selected.iter().any(|other| other.index == candidate.index) {
                selected.push(candidate);
                if selected.len() == num_arms {
                    break;
                }
            }
        }
        Ok(selected)
    }

    /// Compute lower and upper bounds for a specific trust region `r`.
    pub fn compute_bounds(
        &self,
        r: usize,
        lengthscales: Option<&ArrayView1<f64>>,
    ) -> (Array1<f64>, Array1<f64>) {
        let center = self.centers.row(r);
        let len = self.lengths[r];
        let mut lb = Array1::zeros(self.num_dim);
        let mut ub = Array1::zeros(self.num_dim);

        if let Some(ls) = lengthscales {
            let ls_mean = ls.mean().unwrap_or(1.0);
            for d in 0..self.num_dim {
                let half = 0.5 * len * (ls[d] / ls_mean);
                lb[d] = (center[d] - half).clamp(0.0, 1.0);
                ub[d] = (center[d] + half).clamp(0.0, 1.0);
            }
        } else {
            let half = 0.5 * len;
            for d in 0..self.num_dim {
                lb[d] = (center[d] - half).clamp(0.0, 1.0);
                ub[d] = (center[d] + half).clamp(0.0, 1.0);
            }
        }

        (lb, ub)
    }

    /// Update trust regions with newly observed batch points `x_batch` (shape [N, d]) and `y_batch` (shape [N]).
    pub fn tell_update(
        &mut self,
        x_batch: &ArrayView2<f64>,
        y_batch: &ArrayView1<f64>,
    ) -> Result<(), TrustRegionError> {
        self.tell(x_batch, y_batch, None)
    }

    /// Update regions, optionally preserving each observation's generating region.
    pub fn tell(
        &mut self,
        x_batch: &ArrayView2<f64>,
        y_batch: &ArrayView1<f64>,
        regions: Option<&[usize]>,
    ) -> Result<(), TrustRegionError> {
        let n = x_batch.nrows();
        if n == 0 {
            return Ok(());
        }
        if x_batch.ncols() != self.num_dim || y_batch.len() != n {
            return Err(TrustRegionError::InvalidParameter(format!(
                "Batch shapes mismatched: x {:?}, y len {}",
                (x_batch.nrows(), x_batch.ncols()),
                y_batch.len()
            )));
        }
        if let Some(ids) = regions {
            if ids.len() != n || ids.iter().any(|&r| r >= self.num_regions) {
                return Err(TrustRegionError::InvalidParameter(
                    "generating regions do not match the observation batch".to_string(),
                ));
            }
        } else if self.config.sharing_policy == SharingPolicy::Independent {
            return Err(TrustRegionError::InvalidParameter(
                "independent sharing requires generating regions".to_string(),
            ));
        }

        for r in 0..self.num_regions {
            if !self.active_mask[r] {
                continue;
            }

            let mut region_improved = false;
            let current_best = self.incumbents_y[r];
            let mut best_y_in_batch = f64::NEG_INFINITY;
            let mut best_x_idx: Option<usize> = None;

            let (lb, ub) = self.compute_bounds(r, None);

            for i in 0..n {
                let x_i = x_batch.row(i);
                let y_i = y_batch[i];

                let inside = self.accepts(r, i, &x_i, &lb, &ub, regions);

                if regions.is_some_and(|ids| ids[i] == r) {
                    self.record(r, y_i);
                }
                if inside && y_i > current_best && y_i > best_y_in_batch {
                    best_y_in_batch = y_i;
                    best_x_idx = Some(i);
                    region_improved = true;
                }
            }

            if region_improved {
                if let Some(idx) = best_x_idx {
                    self.incumbents_y[r] = y_batch[idx];
                    let x_best = x_batch.row(idx);
                    for d in 0..self.num_dim {
                        self.centers[[r, d]] = x_best[d];
                    }
                }
                self.succ_counts[r] += 1;
                self.fail_counts[r] = 0;

                if self.succ_counts[r] >= self.config.succ_tolerance {
                    self.lengths[r] = (2.0 * self.lengths[r]).min(self.config.length.length_max);
                    self.succ_counts[r] = 0;
                }
            } else {
                self.succ_counts[r] = 0;
                self.fail_counts[r] += 1;

                if self.fail_counts[r] >= self.config.fail_tolerance {
                    self.lengths[r] *= 0.5;
                    self.fail_counts[r] = 0;

                    if self.lengths[r] < self.config.length.length_min {
                        self.active_mask[r] = false; // Flag for restart
                    }
                }
            }
        }

        Ok(())
    }

    /// Restart a inactive region `r` with a new center location.
    pub fn restart_region(
        &mut self,
        r: usize,
        new_center: &ArrayView1<f64>,
    ) -> Result<(), TrustRegionError> {
        if r >= self.num_regions {
            return Err(TrustRegionError::InvalidParameter(format!(
                "region_idx {} out of bounds {}",
                r, self.num_regions
            )));
        }
        if new_center.len() != self.num_dim {
            return Err(TrustRegionError::InvalidParameter(format!(
                "new_center len {} != num_dim {}",
                new_center.len(),
                self.num_dim
            )));
        }

        for d in 0..self.num_dim {
            self.centers[[r, d]] = new_center[d].clamp(0.0, 1.0);
        }
        self.lengths[r] = self.config.length.length_init;
        self.succ_counts[r] = 0;
        self.fail_counts[r] = 0;
        self.incumbents_y[r] = f64::NEG_INFINITY;
        self.active_mask[r] = true;
        self.trial_counts[r] = 0;
        self.mean_y[r] = 0.0;
        self.m2_y[r] = 0.0;

        Ok(())
    }

    fn priority(&self, region: usize, queued: usize, total_trials: f64, utility: f64) -> f64 {
        let trials = self.trial_counts[region] as f64;
        let effective_trials = trials + queued as f64;
        let uncertainty =
            ((total_trials + self.num_regions as f64 + 1.0).ln() / effective_trials).sqrt();
        utility + self.config.exploration * uncertainty
    }

    fn seed_distance(&self, a: u64, b: u64) -> bool {
        (a ^ b).count_ones() as f64 / u64::BITS as f64 >= self.config.min_seed_distance
    }

    fn accepts(
        &self,
        region: usize,
        observation: usize,
        x: &ArrayView1<f64>,
        lb: &Array1<f64>,
        ub: &Array1<f64>,
        regions: Option<&[usize]>,
    ) -> bool {
        match self.config.sharing_policy {
            SharingPolicy::Shared => self.contains(x, lb, ub),
            SharingPolicy::Independent => regions.is_some_and(|ids| ids[observation] == region),
            SharingPolicy::NearestCenter => {
                let distance = self.distance_to(region, x);
                (0..self.num_regions)
                    .filter(|&other| other != region && self.active_mask[other])
                    .all(|other| self.distance_to(other, x) >= distance)
            }
        }
    }

    fn contains(&self, x: &ArrayView1<f64>, lb: &Array1<f64>, ub: &Array1<f64>) -> bool {
        (0..self.num_dim).all(|d| x[d] >= lb[d] && x[d] <= ub[d])
    }

    fn distance_to(&self, region: usize, x: &ArrayView1<f64>) -> f64 {
        let center = self.centers.row(region);
        (0..self.num_dim).map(|d| (x[d] - center[d]).powi(2)).sum()
    }

    fn record(&mut self, region: usize, y: f64) {
        self.trial_counts[region] += 1;
        let n = self.trial_counts[region] as f64;
        let delta = y - self.mean_y[region];
        self.mean_y[region] += delta / n;
        self.m2_y[region] += delta * (y - self.mean_y[region]);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ndarray::array;
    use rand::rngs::StdRng;
    use rand::SeedableRng;

    #[test]
    fn test_001() {
        let mut rng = StdRng::seed_from_u64(42);
        let cfg = MultiTrustRegionConfig::new(4, TRLengthConfig::default());
        let tr = MultiTrustRegionState::new(3, cfg, None, &mut rng).unwrap();

        assert_eq!(tr.num_regions(), 4);
        assert_eq!(tr.num_dim(), 3);
        assert_eq!(tr.active_count(), 4);
        assert_eq!(tr.centers.shape(), &[4, 3]);
    }

    #[test]
    fn test_002() {
        let mut rng = StdRng::seed_from_u64(42);
        let mut cfg = MultiTrustRegionConfig::new(2, TRLengthConfig::default());
        cfg.succ_tolerance = 2;
        cfg.fail_tolerance = 2;

        let init_centers = array![[0.5, 0.5], [0.1, 0.1]];
        let mut tr =
            MultiTrustRegionState::new(2, cfg, Some(&init_centers.view()), &mut rng).unwrap();

        let initial_len0 = tr.lengths[0];

        // Tell improvement near center 0
        let x_batch = array![[0.51, 0.51]];
        let y_batch = array![10.0];
        tr.tell_update(&x_batch.view(), &y_batch.view()).unwrap();
        assert_eq!(tr.succ_counts[0], 1);

        let y_batch2 = array![15.0];
        tr.tell_update(&x_batch.view(), &y_batch2.view()).unwrap();
        assert!(tr.lengths[0] > initial_len0, "Region 0 should expand");
    }

    #[test]
    fn allocation_trajectory() {
        let mut rng = StdRng::seed_from_u64(42);
        let mut tr = MultiTrustRegionState::new(
            2,
            MultiTrustRegionConfig::new(2, Default::default()),
            None,
            &mut rng,
        )
        .unwrap();
        let x = array![[0.1, 0.1], [0.9, 0.9]];
        tr.tell(&x.view(), &array![10.0, 1.0].view(), Some(&[0, 1]))
            .unwrap();

        let plan = tr.allocate(8).unwrap();
        assert!(plan[0].len > plan[1].len);
        assert_eq!(plan.iter().map(|batch| batch.len).sum::<usize>(), 8);
    }

    #[test]
    fn allocation_regions() {
        let mut rng = StdRng::seed_from_u64(42);
        let tr = MultiTrustRegionState::new(
            2,
            MultiTrustRegionConfig::new(2, Default::default()),
            None,
            &mut rng,
        )
        .unwrap();

        let plan = tr.allocate(8).unwrap();
        assert_eq!(
            plan.iter().map(|batch| batch.len).collect::<Vec<_>>(),
            [4, 4]
        );
    }

    #[test]
    fn allocation_utility() {
        let mut rng = StdRng::seed_from_u64(42);
        let tr = MultiTrustRegionState::new(
            2,
            MultiTrustRegionConfig::new(2, Default::default()),
            None,
            &mut rng,
        )
        .unwrap();

        let plan = tr.allocate_with(6, &array![0.0, 10.0].view()).unwrap();
        assert!(plan[1].len > plan[0].len);
        assert!(tr.allocate_with(6, &array![f64::NAN].view()).is_err());
    }

    #[test]
    fn allocation_budgets() {
        let mut rng = StdRng::seed_from_u64(42);
        let mut tr = MultiTrustRegionState::new(
            2,
            MultiTrustRegionConfig::new(4, Default::default()),
            None,
            &mut rng,
        )
        .unwrap();
        tr.mean_y = array![1.0, 4.0, 2.0, 3.0];

        let plan = tr.allocate(2).unwrap();
        assert_eq!(plan.len(), 2);
        assert_eq!(plan.iter().map(|batch| batch.len).sum::<usize>(), 2);
        assert!(plan.iter().all(|batch| batch.len == 1));
        assert!(plan[0].region != plan[1].region);
    }

    #[test]
    fn selection_diverse() {
        let mut rng = StdRng::seed_from_u64(42);
        let mut cfg = MultiTrustRegionConfig::new(2, Default::default());
        cfg.min_seed_distance = 0.25;
        let tr = MultiTrustRegionState::new(2, cfg, None, &mut rng).unwrap();
        let candidates = [
            RegionCandidate {
                index: 0,
                region: 0,
                seed: 0,
                score: 9.0,
            },
            RegionCandidate {
                index: 1,
                region: 0,
                seed: 1,
                score: 8.0,
            },
            RegionCandidate {
                index: 2,
                region: 1,
                seed: u64::MAX,
                score: 7.0,
            },
        ];

        let selected = tr.select(&candidates, 2).unwrap();
        assert_eq!(selected.iter().map(|c| c.index).collect::<Vec<_>>(), [0, 2]);
    }

    #[test]
    fn independent_region() {
        let mut rng = StdRng::seed_from_u64(42);
        let mut cfg = MultiTrustRegionConfig::new(2, Default::default());
        cfg.sharing_policy = SharingPolicy::Independent;
        let centers = array![[0.5], [0.5]];
        let mut tr = MultiTrustRegionState::new(1, cfg, Some(&centers.view()), &mut rng).unwrap();

        assert!(tr
            .tell_update(&array![[0.5]].view(), &array![3.0].view())
            .is_err());
        tr.tell(&array![[0.5]].view(), &array![3.0].view(), Some(&[1]))
            .unwrap();
        assert_eq!(tr.incumbents_y[0], f64::NEG_INFINITY);
        assert_eq!(tr.incumbents_y[1], 3.0);
        assert_eq!(tr.trial_counts, [0, 1]);
        tr.tell(&array![[0.6]].view(), &array![5.0].view(), Some(&[1]))
            .unwrap();
        assert_eq!(tr.variance(1), Some(2.0));
        assert_eq!(tr.variance(2), None);
    }

    #[test]
    fn nearest_explicit() {
        let mut rng = StdRng::seed_from_u64(42);
        let mut cfg = MultiTrustRegionConfig::new(2, Default::default());
        cfg.sharing_policy = SharingPolicy::NearestCenter;
        cfg.min_seed_distance = 0.5;
        let centers = array![[0.0], [1.0]];
        let tr = MultiTrustRegionState::new(1, cfg, Some(&centers.view()), &mut rng).unwrap();
        let x = array![0.1];
        let lb = array![0.0];
        let ub = array![1.0];

        assert!(tr.accepts(0, 0, &x.view(), &lb, &ub, None));
        assert!(!tr.accepts(1, 0, &x.view(), &lb, &ub, None));
        assert!(tr.distance_to(0, &x.view()) < tr.distance_to(1, &x.view()));
        assert!(tr.seed_distance(0, u64::MAX));
        assert!(!tr.seed_distance(0, 1));
    }
}
