filegroup(
    name = "source",
    srcs = glob(["**/*.rs"]) + [
        "Cargo.lock",
        "Cargo.toml",
        "kernels/Cargo.toml",
        "rust-toolchain.toml",
    ],
    visibility = ["PUBLIC"],
)
