[package]
name = "ennx-cuda"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]
members = ["kernels"]
resolver = "2"

[workspace.dependencies]
cuda-core = { git = "https://github.com/NVlabs/cuda-oxide.git", rev = "1f4d813719012d384f2db12b88efc9314c8bf50c" }
cuda-device = { git = "https://github.com/NVlabs/cuda-oxide.git", rev = "1f4d813719012d384f2db12b88efc9314c8bf50c" }
cuda-host = { git = "https://github.com/NVlabs/cuda-oxide.git", rev = "1f4d813719012d384f2db12b88efc9314c8bf50c" }

[dependencies]
cuda-core.workspace = true
cuda-host.workspace = true
ennx-cuda-kernels = { path = "kernels" }
tracy-client = { version = "=0.18.4", default-features = false, features = ["enable", "timer-fallback"] }
