[package]
name = "ennx-cuda"
version = "0.2.0"
edition = "2024"
publish = false

[features]
native-flame = []

[dependencies]
cuda-core.workspace = true
cuda-host.workspace = true
ennx-cuda-kernels = { path = "kernels" }
ennx-wire.workspace = true
memmap2 = "0.9"
deser.workspace = true
ptx-synth.workspace = true
half = "2.7"
