load("//buck2:reindeer_rules.bzl", "app_rust_binary")

app_rust_binary(
    name = "ennx",
    srcs = glob(["src/**/*.rs"]),
    crate = "dev_cli",
    crate_root = "src/main.rs",
    edition = "2021",
    deps = [
        "//rust/crates/ennx:ennx",
        "//rust:ndarray",
        "//rust:rand",
        "//rust:toml",
    ] + select({
        "//:macos-arm64": ["//buck2/native:openmp-macos"],
        "DEFAULT": [],
    }),
    rpath = True,
    runtime_dependency_handling = "symlink",
    rustc_flags = select({
        "//:macos-arm64": [
            "-Clink-arg=-Wl,-rpath,@loader_path/../../../../buck2/native/__faiss-build__/out",
        ],
        "DEFAULT": [],
    }),
    visibility = ["PUBLIC"],
)

rust_test(
    name = "ennx-test",
    srcs = glob(["src/**/*.rs"]),
    crate = "dev_cli_test",
    crate_root = "src/main.rs",
    edition = "2021",
    deps = [
        "//rust/crates/ennx:ennx",
        "//rust:ndarray",
        "//rust:rand",
        "//rust:toml",
    ] + select({
        "//:macos-arm64": ["//buck2/native:openmp-macos"],
        "DEFAULT": [],
    }),
    rpath = True,
    runtime_dependency_handling = "symlink",
    rustc_flags = select({
        "//:macos-arm64": [
            "-Clink-arg=-Wl,-rpath,@loader_path/../../../../buck2/native/__faiss-build__/out",
        ],
        "DEFAULT": [],
    }),
)
