[package]
name = "ennx-dev-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
default-run = "ennx"

[dependencies]
clap.workspace = true
ennx.workspace = true
ndarray.workspace = true
rand.workspace = true
deser.workspace = true
ennx-wire.workspace = true
ptx-synth.workspace = true
sha2.workspace = true
